/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marioparty;


import Reproductor.SongThread;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Joctan Esquivel
 */
public class DadosEscogerOrden extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    DatosMenuPrimerUsuario x;
    ImageIcon[] arrayImages=new ImageIcon[6];
    public DadosEscogerOrden(DatosMenuPrimerUsuario x) {
        this.x = x;
        
        
        
        initComponents();
        System.out.println(this.x.nombreJugador);
        System.out.println(this.x.numeroJugadores);
        setImages();
        this.lblDado1.setIcon(arrayImages[0]);
        this.lblDado2.setIcon(arrayImages[1]);
        
    }
    
    
    private void setImages(){
        arrayImages[0] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado1.png");
        arrayImages[1] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado2.png");
        arrayImages[2] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado3.png");
        arrayImages[3] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado4.png");
        arrayImages[4] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado5.png");
        arrayImages[5] = new ImageIcon("C:\\Users\\Joctan Esquivel\\Documents\\TEC\\Semestre II\\POO\\Proyecto2\\MarioParty\\src\\fotos\\dado6.png");
    }
    
    
    
    
    
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloGenerico = new javax.swing.JLabel();
        lblSubtitilo = new javax.swing.JLabel();
        lblDado2 = new javax.swing.JLabel();
        lblDado1 = new javax.swing.JLabel();
        btnLanzaDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 49, 49));

        lblTituloGenerico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloGenerico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloGenerico.setText("Lance los dados para escoger el orden en el cual jugarán");

        lblSubtitilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubtitilo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtitilo.setText("¡¡Suerte!!");

        lblDado2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDado1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLanzaDados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLanzaDados.setText("Lanzar Dados");
        btnLanzaDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzaDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloGenerico, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtitilo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLanzaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitilo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnLanzaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private int giraDados(JLabel dado1,JLabel dado2, JFrame pantalla){
        
        
        
        Timer tiempo = new Timer();
        TimerTask girar = null;
        girar = new TimerTask() {
            int contador =0;
            @Override
            public void run() {
                int num1 = (int) (Math.random()*5+1);
                int num2 = (int) (Math.random()*5+1);
                if (contador==12){
                    cancel();
                    dado1.setIcon(arrayImages[num1]);
                    dado2.setIcon(arrayImages[num2]);
                    JOptionPane.showMessageDialog(pantalla,"Has obtenido un "+((num1+1)+(num2+1)), "Puntos Obtenidos", 1);
                    
                }
                
                
                    
               dado1.setIcon(arrayImages[num1]);
               dado2.setIcon(arrayImages[num2]);
                contador++;
               
            }
            
        };
        
      
            tiempo.schedule(girar,0,250);
        int num1 = (int) (Math.random()*5+1);
        int num2 = (int) (Math.random()*5+1);
                        
        dado1.setIcon(arrayImages[num1]);
        dado2.setIcon(arrayImages[num2]);
        return num1+num2;
        
    }
    private void btnLanzaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzaDadosActionPerformed
        // TODO add your handling code here:
        int numero = giraDados(this.lblDado1,lblDado2,this);
        SongThread cancion = new SongThread("sonidoDados.wav"); 
        cancion.start();
        
        System.out.println(lblDado1.getIcon().toString());
   
         
                
	
        
        
            
        
        
        
    }//GEN-LAST:event_btnLanzaDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosEscogerOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosEscogerOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosEscogerOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosEscogerOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzaDados;
    private javax.swing.JLabel lblDado1;
    private javax.swing.JLabel lblDado2;
    private javax.swing.JLabel lblSubtitilo;
    private javax.swing.JLabel lblTituloGenerico;
    // End of variables declaration//GEN-END:variables
}
